# $Id: Makefile,v 1.2 2002/07/20 02:02:13 ehood Exp $

.PHONY: default

TOP     = ../..
SUBDIRS = \
	  CharEnt \
	  # End SUBDIRS

PERL_PM_FILES = \
		CharEnt.pm \
		# End PERL_PM_FILES

include $(TOP)/etc/variables.mk


default: make_subdirs perl_syntax


include $(TOP)/etc/rules.mk
