##---------------------------------------------------------------------------##
##  File:
##      $Id: ISO8859_15.pm,v 1.4 2003/01/05 21:17:04 ehood Exp $
##  Author:
##      Earl Hood       earl@earlhood.com
##	Jan Kraeber	jmk@kraeber.de
##  Description:
##      Mappings for ISO-8859-15.
##---------------------------------------------------------------------------##

package MHonArc::CharEnt::ISO8859_15;

## ISO-8859-15: Latin-9
+{

  # Hex Code	Entity Ref

    '¡',	'&iexcl;',
    '¢',	'&cent;',
    '£',	'&pound;',
    '¤',	'&euro;',
    '¥',	'&yen;',
    '¦',	'&Scaron;',
    '§',	'&sect;',
    '¨',	'&scaron;',
    '©',	'&copy;',
    'ª',	'&ordf;',
    '«',	'&laquo;',
    '¬',	'&not;',
    '­',	'&shy;',
    '®',	'&reg;',
    '¯',	'&macr;',
    '°',	'&deg;',
    '±',	'&plusmn;',
    '²',	'&sup2;',
    '³',	'&sup3;',
#   '´',	'&Zcaron;',
    '´',	'&#x17D;',
    'µ',	'&micro;',
    '¶',	'&para;',
    '·',	'&middot;',
#   '¸',	'&zcaron;',
    '¸',	'&#x17E;',
    '¹',	'&sup1;',
    'º',	'&ordm;',
    '»',	'&raquo;',
    '¼',	'&OElig;',
    '½',	'&oelig;',
    '¾',	'&Yuml;',
    '¿',	'&iquest;',
    'À',	'&Agrave;',
    'Á',	'&Aacute;',
    'Â',	'&Acirc;',
    'Ã',	'&Atilde;',
    'Ä',	'&Auml;',
    'Å',	'&Aring;',
    'Æ',	'&AElig;',
    'Ç',	'&Ccedil;',
    'È',	'&Egrave;',
    'É',	'&Eacute;',
    'Ê',	'&Ecirc;',
    'Ë',	'&Euml;',
    'Ì',	'&Igrave;',
    'Í',	'&Iacute;',
    'Î',	'&Icirc;',
    'Ï',	'&Iuml;',
    'Ð',	'&ETH;',
    'Ñ',	'&Ntilde;',
    'Ò',	'&Ograve;',
    'Ó',	'&Oacute;',
    'Ô',	'&Ocirc;',
    'Õ',	'&Otilde;',
    'Ö',	'&Ouml;',
    '×',	'&times;',
    'Ø',	'&Oslash;',
    'Ù',	'&Ugrave;',
    'Ú',	'&Uacute;',
    'Û',	'&Ucirc;',
    'Ü',	'&Uuml;',
    'Ý',	'&Yacute;',
    'Þ',	'&THORN;',
    'ß',	'&szlig;',
    'à',	'&agrave;',
    'á',	'&aacute;',
    'â',	'&acirc;',
    'ã',	'&atilde;',
    'ä',	'&auml;',
    'å',	'&aring;',
    'æ',	'&aelig;',
    'ç',	'&ccedil;',
    'è',	'&egrave;',
    'é',	'&eacute;',
    'ê',	'&ecirc;',
    'ë',	'&euml;',
    'ì',	'&igrave;',
    'í',	'&iacute;',
    'î',	'&icirc;',
    'ï',	'&iuml;',
    'ð',	'&eth;',
    'ñ',	'&ntilde;',
    'ò',	'&ograve;',
    'ó',	'&oacute;',
    'ô',	'&ocirc;',
    'õ',	'&otilde;',
    'ö',	'&ouml;',
    '÷',	'&divide;',
    'ø',	'&oslash;',
    'ù',	'&ugrave;',
    'ú',	'&uacute;',
    'û',	'&ucirc;',
    'ü',	'&uuml;',
    'ý',	'&yacute;',
    'þ',	'&thorn;',
    'ÿ',	'&yuml;',
};
