# $Id: Makefile,v 1.1 2002/04/01 07:34:02 ehood Exp $

.PHONY: default

TOP     = ../../..
SUBDIRS = \
	  # End SUBDIRS

include $(TOP)/etc/variables.mk


default: perl_syntax


include $(TOP)/etc/rules.mk
