# $Id: Makefile,v 1.2 2002/04/01 07:33:37 ehood Exp $

.PHONY: default

TOP     = ..
SUBDIRS = \
	  MHonArc \
	  # End SUBDIRS

include $(TOP)/etc/variables.mk


default: make_subdirs perl_syntax


include $(TOP)/etc/rules.mk
